// Auto-generated Schema types from amplify_outputs.json
// This file is generated based on your backend schema

import { type ClientSchema, a, defineData } from '@aws-amplify/backend';

// This is a placeholder schema type
// The actual types are generated by Amplify based on amplify_outputs.json
export type Schema = ClientSchema<any>;

export const schema = a.schema({});

export const data = defineData({
  schema
});
